#include <stdio.h>
#include <math.h>

int main()
{
    char noisyString[] = "0010011";
    int existingCodeword[7]; // where all existing codewords should be
    int existingBits[4];     // 4 bits for hammig 7,4
    int nString[7] = {0};

    double pnoisezero = 0.0001; // p 0 -> 1
    double pnoiseminuszero = 1 - pnoisezero;

    double pnoiseone = 0.4; // p 1 -> 0
    double pnoiseminusone = 1 - pnoiseone;

    double ptintyMax = 0;
    int zeroesdiff = 0;
    int onesdiff = 0;
    int onecount = 0;
    int zerocount = 0;
    int val;
    // Random values generated by value = rand() % 100 + 1;

    int differences = 0;

    double ptinty;

    for (int i = 0; i < 7; i++)
    {
        nString[i] = noisyString[i] - '0';
    }

    for (int valCheck = 0; valCheck < 16; valCheck++)
    {
        zerocount = 0;
        onecount = 0;
        zeroesdiff = 0;
        onesdiff = 0;
        differences = 0;
        val = valCheck;

        for (int j = 0; j < 4; j++)
        {
            existingBits[j] = val % 2;
            if (existingBits[j] == 1)
            {
                val = val - 1;
            }
            val = val / 2;
        }

        existingCodeword[0] = existingBits[0] + existingBits[1] + existingBits[3];
        existingCodeword[1] = existingBits[0] + existingBits[2] + existingBits[3];
        existingCodeword[2] = existingBits[0];
        existingCodeword[3] = existingBits[1] + existingBits[2] + existingBits[3];
        existingCodeword[4] = existingBits[1];
        existingCodeword[5] = existingBits[2];
        existingCodeword[6] = existingBits[3];

        for (int i = 0; i < 7; i++)
        {
            existingCodeword[i] = (existingCodeword[i] % 2);
        }

        for (int i = 0; i < 7; i++)
        {
            if (existingCodeword[i] == 1)
            {
                onecount++;
                if (existingCodeword[i] != nString[i])
                {
                    onesdiff++;
                    differences++; // get the differences in the codewords
                }
            }
            else
            {
                zerocount++;
                if (existingCodeword[i] != nString[i])
                {
                    zeroesdiff++;
                    differences++; // get the differences in the codewords
                }
            }
        }

        // ptinty = pow(pnoise, differences) * pow(minuspnoise, (7 - differences));
        ptinty = pow(pnoiseone, onesdiff) * pow(pnoisezero, zeroesdiff) * pow(pnoiseminusone, (onecount - onesdiff)) * pow(pnoiseminuszero, (zerocount - zeroesdiff));

        if (ptinty > ptintyMax)
        {
            printf("Current most likely codeword:\n");
            printf("%d%d%d%d%d%d%d\n", existingCodeword[0], existingCodeword[2], existingCodeword[2], existingCodeword[3], existingCodeword[4], existingCodeword[5], existingCodeword[6]);
            printf("%f\n", ptinty);
            ptintyMax = ptinty;
        }
        // printf("%d%d%d%d\n", existingBits[0], existingBits[1], existingBits[2], existingBits[3]);
    }

    return 0;
}